services:
  www:
    build: .
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql  # This mounts the volume to store MySQL data persistently

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  
volumes:
  db_data: